# Kakao OAuth 설정
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: a226f00454eb1b297737c5a9e4af6091
            client-secret: ExoaOHs72Bm6e0051xPe6MRCmbh7gAEi
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname
          naver:
            client-id: qECPn87eKQj2jORgYmsj
            client-secret: 66hn8P5D0t
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope: email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response